// <auto-generated />
using System;
using Api.Beneficiarios.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Api.Beneficiarios.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251122200601_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Api.Beneficiarios.Domain.Entities.Beneficiario", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("Id");

                    b.Property<string>("CPF")
                        .IsRequired()
                        .HasMaxLength(11)
                        .HasColumnType("character varying(11)")
                        .HasColumnName("CPF");

                    b.Property<DateTime>("DataAtualizacao")
                        .HasColumnType("timestamp")
                        .HasColumnName("DataAtualizacao");

                    b.Property<DateTime>("DataCadastro")
                        .HasColumnType("timestamp")
                        .HasColumnName("DataCadastro");

                    b.Property<DateTime?>("DataExclusao")
                        .HasColumnType("timestamp")
                        .HasColumnName("DataExclusao");

                    b.Property<DateTime>("DataNascimento")
                        .HasColumnType("date")
                        .HasColumnName("DataNascimento");

                    b.Property<bool>("Excluido")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("Excluido");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("Nome");

                    b.Property<Guid>("PlanoId")
                        .HasColumnType("uuid")
                        .HasColumnName("PlanoId");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("Status");

                    b.HasKey("Id");

                    b.HasIndex("CPF")
                        .IsUnique()
                        .HasDatabaseName("IX_Beneficiarios_CPF");

                    b.HasIndex("Excluido")
                        .HasDatabaseName("IX_Beneficiarios_Excluido");

                    b.HasIndex("PlanoId")
                        .HasDatabaseName("IX_Beneficiarios_PlanoId");

                    b.HasIndex("Status")
                        .HasDatabaseName("IX_Beneficiarios_Status");

                    b.HasIndex("Status", "PlanoId")
                        .HasDatabaseName("IX_Beneficiarios_Status_PlanoId");

                    b.ToTable("Beneficiarios", (string)null);
                });

            modelBuilder.Entity("Api.Beneficiarios.Domain.Entities.Plano", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("Id");

                    b.Property<string>("CodRegistroAns")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("CodRegistroAns");

                    b.Property<DateTime>("DataAtualizacao")
                        .HasColumnType("timestamp")
                        .HasColumnName("DataAtualizacao");

                    b.Property<DateTime>("DataCadastro")
                        .HasColumnType("timestamp")
                        .HasColumnName("DataCadastro");

                    b.Property<DateTime?>("DataExclusao")
                        .HasColumnType("timestamp")
                        .HasColumnName("DataExclusao");

                    b.Property<bool>("Excluido")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("Excluido");

                    b.Property<string>("NomePlano")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("NomePlano");

                    b.Property<bool>("StatusPlano")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("StatusPlano");

                    b.HasKey("Id");

                    b.HasIndex("CodRegistroAns")
                        .IsUnique()
                        .HasDatabaseName("IX_Planos_CodRegistroANS");

                    b.HasIndex("Excluido")
                        .HasDatabaseName("IX_Planos_Excluido");

                    b.HasIndex("NomePlano")
                        .IsUnique()
                        .HasDatabaseName("IX_Planos_Nome");

                    b.HasIndex("StatusPlano")
                        .HasDatabaseName("IX_Planos_StatusPlano");

                    b.ToTable("Planos", (string)null);
                });

            modelBuilder.Entity("Api.Beneficiarios.Domain.Entities.Beneficiario", b =>
                {
                    b.HasOne("Api.Beneficiarios.Domain.Entities.Plano", "Plano")
                        .WithMany("Beneficiarios")
                        .HasForeignKey("PlanoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_Beneficiarios_Planos");

                    b.Navigation("Plano");
                });

            modelBuilder.Entity("Api.Beneficiarios.Domain.Entities.Plano", b =>
                {
                    b.Navigation("Beneficiarios");
                });
#pragma warning restore 612, 618
        }
    }
}
